# Generated by Django 6.0.7 on 2026-09-07 14:25

from django.db import migrations


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("software_cost", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task_master",
            name="task_priority",
            field=models.CharField(
                max_length=50,
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                ],
                default="Medium",
            ),
        ),
        migrations.AddField(
            model_name="task_master",
            name="task_duration",
            field=models.DurationField(
                null=True,
                blank=True,
            ),
        ),
    ]
