# Generated by Django 6.0.7 on 2026-09-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0002_add_task_priority_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_master',
            name='working_hours',
        ),
        migrations.AlterField(
            model_name='task_master',
            name='task_priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=50),
        ),
    ]
