# Generated by Django 6.0.7 on 2026-09-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0003_remove_user_master_working_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_master',
            name='working_hours_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
